# .ide/Dockerfile

FROM cnbcool/default-dev-env:latest

RUN curl -fsSL https://cli.moonbitlang.cn/install/unix.sh | bash \
  && code-server --install-extension moonbit.moonbit-lang \
  && echo Hello MoonBit
